### ISSUE TITLE
Killed the command

### ISSUE THREAD

**Issue by JesseBNL** [yeeus/GCI#11]
Dear yeeus,

I think this is an excellent tool to map the depth and gaps of an assembly, but it does not succeed for me. It keeps killing the command after running for a while:

```
Finding gaps ...
Finding gaps done!!! The gaps are in ../final_assemblies/GCI.gaps.bed


Filtering HiFi alignment files ...
Filtering HiFi alignment files done!!!
Writing depths into "../final_assemblies/GCI_hifi.depth.gz" ...
Writing depths done!!!


Filtering ONT alignment files ...
Killed
```

Also when I try to plot the hifi depth using the generated GCI_hifi.depth.gz file and the stand-alone utility, it kills the command. Can the memory management for this script be optimized?

**Comment by yeeus** [comment]
Actually, this problem was caused mainly due to memory usage which was metioned in the `To do` section of README. And the solution is always increasing your memory allocation. I'm sorry for the memory issue again. and I wish someday I would improve it!

**Comment by yeeus** [comment]
I will close this issue due to long time of inactivity.
