### ISSUE TITLE
issues for specific region 

### ISSUE THREAD

**Issue by ssssyq1123** [yeeus/GCI#5]
Cool tool! I’m interested in specific regions, but I’m running into some issues with GCI.
1. Is it possible to generate a continuity index for a specific region?
2. When I plot the depth of a specific region, it also generates whole genome figures, which takes a long time. It doesn’t seem necessary, though.
3. It’d be awesome to add some logging since the tool needs a lot of memory. I keep hitting an ‘out of memory’ error in the first few runs, but I can’t check if the depth file has been generated. If you’ve got a log file, could you please check the last log entry so I can keep the GCI running?

**Comment by yeeus** [comment]
1. Yeah, in the newest version of GCI (v0.4), I added the function to generate GCI scores for each specific region.
2. As GCI is a tool for assesing genome continuity while plotting is just an additional function, GCI would plot all chromosomes in defaut. However, in the latest version, the script plot_depth.py in the directory `utility` can generate plots only for the sepcific regions if providing `-R` option (as descripted in #4)
3. I'm so sorry for that, `out of memory` also happens to me usually. I do think I need to solve this problem some day. And good suggestions, I have added the funcion of logging in the latest version of GCI (v0.4), I wish that would help you...

**Comment by ssssyq1123** [comment]
Thanks for quick reply and update!   
Could you please provide a  separate script for  GCI score calculation of specific region like the plot script in the utility?  Then I have not to run the whole process again since I got the depth.gz already~

**Comment by yeeus** [comment]
Yeah that's a good suggestion. Now in the latest commit, I created a file named `GCI_score.py` in the folder `utility`, which can be used to compute GCI score as in GCI.py and all you need is to provide the depth.gz file you got.

**Comment by yeeus** [comment]
I will close this issue due to long time of inactivity.
