### ISSUE TITLE
some questions about input file

### ISSUE THREAD

**Issue by Hanjunmin** [yeeus/GCI#6]
Hi,
It's a great tool!
but i don't know how to input my depth file when used the plot_depth.py,can you give me an example? I also suggest that you cam add some unusual input sample files on github.
Thank you

**Comment by yeeus** [comment]
The depth file provided for plot_depth.py is generated by GCI which is in a fasta-like format (and gzipped):
```
>chromosome_id
0
1
2
3
...
```

And if you only need to use plot_depth.py with your customed depth file (such as the outputs from `samtools depth`), you can convert that into this format. And I will provide a script for that later (you would see it in the directory `utility`). Could you show me the format of your depth file?

**Comment by yeeus** [comment]
I will close this issue due to long time of inactivity.
