### ISSUE TITLE
a summarized GCI score for multiple specific regions

### ISSUE THREAD

**Issue by dongyawu** [yeeus/GCI#7]
Hi, Quanyu! thanks for your efforts to improve this nice tool.
I am evaluating the assembly quality of centromeres and GCI can generate the score of a specific region. how about generating a summarized GCI score for multiple regions? just like a whole-genome score?

**Comment by yeeus** [comment]
Now, in the latest beta version (commit `9a15e91`), you can get a summarized GCI score in the file named `${prefix}.regions.gci` if providing regions file with `-R`

**Comment by yeeus** [comment]
I will close this issue due to long time of inactivity.
